variables:
  POSTMAN_COLLECTION: https://api.getpostman.com/collections/${c_uid}?apikey=${apiKey}
  POSTMAN_ENVIRONMENT: https://api.getpostman.com/environments/${e_uid}?apikey=${apiKey}

stages:
- some_stages
- postman

postman_job:
  stage: postman
  image: wojciechzurek/newman-ci
  script:
  - newman run ${POSTMAN_COLLECTION} -e ${POSTMAN_ENVIRONMENT}
