version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build the Docker image
          command: docker build . --file Dockerfile        

  test:
    docker:
      - image: benweese/postman
    steps:
      - checkout
      - run:
          name: News API
          command: newman run newsapi.org.postman_collection.json 
                    -e newsapi.org.postman_environment.json 
                    -x -r htmlextra --reporter-htmlextra-darkTheme 
                    ~/test-results/newsapi.html
      - run:
          name: Swapi API
          command: newman run SWAPI.postman_collection.json 
                    -x -r htmlextra --reporter-htmlextra-darkTheme 
                    ~/test-results/swapi.html
      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: ~/test-results
      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: ~/test-results/
         
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
