version: 2.1
orbs:
  newman: postman/newman@4.4.1
jobs:
  newman-collection-run-env-timeout:
    executor: newman/postman-newman-docker
    steps:
      - checkout
      - newman/newman-run:
          collection: ./newsapi.org.postman_collection.json
          environment: ./newsapi.org.postman_environment.json
          timeout: '1000'
