name: Node CI

on: [push]

jobs:
  build:

    runs-on: macOS-10.14

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependancies
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra
    - name: Run Newsapi Test
        run: newman run newsapi.org.postman_collection.json -e newsapi.org.postman_environment.json -k -x -r cli,htmlextra --reporter-htmlextra-darkTheme
   - name: Run SWAPI GraphQL Test
      run: newman run SWAPI.postman_collection.json -k -x -r cli,htmlextra --reporter-htmlextra-darkTheme
